# Generated by Django 2.2.3 on 2023-02-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20230216_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='color_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='hex_code',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='matching_outfit',
            field=models.ManyToManyField(blank=True, related_name='_item_matching_outfit_+', to='core.Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='Measurements',
            field=models.ManyToManyField(blank=True, to='core.Measurements'),
        ),
        migrations.AddField(
            model_name='item',
            name='body_type',
            field=models.ManyToManyField(to='core.BodyType'),
        ),
        migrations.AddField(
            model_name='item',
            name='occasion',
            field=models.ManyToManyField(to='core.Occasion'),
        ),
        migrations.AddField(
            model_name='item',
            name='weather',
            field=models.ManyToManyField(to='core.Weather'),
        ),
    ]
