# Generated by Django 2.2.3 on 2023-02-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dresstype',
            name='wearing_part',
            field=models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom')], default='top', max_length=20),
        ),
    ]
