# Generated by Django 2.2.3 on 2023-02-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20230219_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='wearing_part',
            field=models.CharField(choices=[('top_piece', 'Top Piece'), ('bottom_piece', 'Bottom Piece'), ('one_piece', 'One Piece'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
