# Generated by Django 2.2.3 on 2023-02-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20230219_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='body_type',
            field=models.ManyToManyField(blank=True, to='core.BodyType'),
        ),
    ]
