# Generated by Django 2.2.3 on 2023-02-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20230219_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='gender',
        ),
        migrations.AddField(
            model_name='item',
            name='gender',
            field=models.ManyToManyField(blank=True, to='core.Gender'),
        ),
    ]
