# Generated by Django 2.2.3 on 2023-02-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20230219_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='user'),
        ),
        migrations.AddField(
            model_name='profile',
            name='under_tone',
            field=models.CharField(blank=True, choices=[('W', 'Warm'), ('C', 'Cool'), ('N', 'Neutral')], max_length=1, null=True),
        ),
    ]
