# Generated by Django 2.2.3 on 2023-02-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20230220_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='back_image',
            field=models.ImageField(blank=True, upload_to='user/back'),
        ),
        migrations.AddField(
            model_name='profile',
            name='front_image',
            field=models.ImageField(blank=True, upload_to='user/front'),
        ),
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
