# Generated by Django 2.2.3 on 2023-03-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20230220_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='vton_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
