# Generated by Django 2.2.3 on 2023-03-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_item_vton_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='vton_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
