# Generated by Django 2.2.3 on 2023-04-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20230308_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='edge_image',
            field=models.ImageField(blank=True, null=True, upload_to='edge'),
        ),
        migrations.AlterField(
            model_name='item',
            name='vton_image',
            field=models.ImageField(blank=True, null=True, upload_to='vton'),
        ),
    ]
