# Generated by Django 2.2.3 on 2023-04-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20230425_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='label_image',
            field=models.ImageField(blank=True, upload_to='user/label'),
        ),
    ]
