# Generated by Django 2.2.3 on 2023-04-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_profile_label_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pose_keypoints',
            field=models.FileField(blank=True, upload_to='user/pose_keypoints'),
        ),
    ]
