# Generated by Django 2.2.3 on 2023-04-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_profile_pose_keypoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='process_image',
            field=models.BooleanField(default=False),
        ),
    ]
