# Generated by Django 2.2.3 on 2023-04-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.ManyToManyField(blank=True, to='core.Gender'),
        ),
    ]
